<?php

namespace Application\Controllers;

// use Application\Core\User;
use Phalcon\Mvc\View;

class UserController extends ControllerBase {
    public function beforeExecuteRoute($dispatcher)
    {
        // dd('dor');
        parent::beforeExecuteRoute($dispatcher); // TODO: Change the autogenerated stub
    }

    public function readAction()
    {
        // dd('dor');
        $this->view->disable();
        echo "Hello users";
    }
}

